# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='zoom',
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
