# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_tourist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityname', models.CharField(blank=True, choices=[('RE', 'Restaurant'), ('CF', 'Cafe'), ('BH', 'Banquet hall'), ('SR', 'Seminar room'), ('CR', 'Conference room'), ('BC', 'Business center'), ('FC', 'Fitness center'), ('MA', 'Massage'), ('SP', 'Swimming pool')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, choices=[('SD', 'Standard double'), ('ST', 'Standard twin'), ('SO', 'Standard ondol'), ('DD', 'Deluxe double'), ('DT', 'Deluxe twin'), ('DO', 'Deluxe ondol'), ('SR', 'Suite room')], max_length=2, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tourist',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='roomtype',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
        migrations.AddField(
            model_name='facility',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
    ]
