# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20180412_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityname',
            field=models.CharField(blank=True, choices=[('RE', 'Restaurant'), ('CF', 'Cafe'), ('BH', 'Banquet hall'), ('SR', 'Seminar room'), ('CR', 'Conference room'), ('BC', 'Business center'), ('FC', 'Fitness center'), ('MA', 'Massage'), ('SP', 'Spa'), ('SN', 'Sauna'), ('SW', 'Swimming pool')], max_length=2, null=True),
        ),
    ]
